### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by xiela123** [HEEKDragonOne/FirstBlood#1]
用户名和密码都对的上，但登录失败，改了后台就算成功了也不会跳转，求助求助

**Comment by HEEKDragonOne** [comment]
是不是密码的问题。数据库中的密码是加密后的。

**Comment by HEEKDragonOne** [comment]
在sql文件的用户表上面添加了一句sql语句，用来添加一个超级管理员的

**Comment by xiela123** [comment]
> 在sql文件的用户表上面添加了一句sql语句，用来添加一个超级管理员的

是哪一句啊，没有看到

**Comment by HEEKDragonOne** [comment]
我更新了sql文件，你可以在仓库直接看sql文件中用户表上面新增的sql语句

**Comment by xiela123** [comment]
进去后左边侧边栏只显示一个首页
          <div v-for="item in menuData" :key="item.id+''">
            <el-sub-menu :index="item.id+''">
              <template #title>
                <el-icon><component :is="item.menuIco"></component></el-icon>
                <b v-show="logoTextShow">{{ item.menuName }}</b>
              </template>
              <div v-for="subItem in item.children" :key="subItem.id+ ''">
                <el-menu-item :index="subItem.menuPath">
                  <el-icon><component :is="subItem.menuIco"></component></el-icon>
                  {{ subItem.menuName }}
                </el-menu-item>
              </div>
            </el-sub-menu>
          </div>
这一段没有跑起来好像

**Comment by xiela123** [comment]
> 我更新了sql文件，你可以在仓库直接看sql文件中用户表上面新增的sql语句

进去后左边侧边栏只有一个首页，view/index.vue里28-41行的代码似乎没有运行

**Comment by HEEKDragonOne** [comment]
这个应该是权限表里面没有数据，所以没有加载侧边栏

**Comment by HEEKDragonOne** [comment]
仓库已更新，增加了初始数据

**Comment by xiela123** [comment]
> 仓库已更新，增加了初始数据

运行了，这次一点登录就报错了

**Comment by xiela123** [comment]
> 仓库已更新，增加了初始数据

2022-04-17 21:56:46.434 ERROR 22988 --- [nio-8081-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

**Comment by jzxhcm** [comment]
直接把SQL文件一次性执行一遍就行了

**Comment by xiela123** [comment]
> 直接把SQL文件一次性执行一遍就行了

直接运行sql文件我之前失败了，我只能分开来一段一段运行

**Comment by 1pjllllove** [comment]
你失败了是因为创建了数据库tothefor后，并没有使用，在创建语句后添加一句 use tothefor; 就行了

**Comment by xiela123** [comment]
> 你失败了是因为创建了数据库tothefor后，并没有使用，在创建语句后添加一句 use tothefor;

> 你失败了是因为创建了数据库tothefor后，并没有使用，在创建语句后添加一句 use tothefor; 就行了

还是报错

**Comment by xiela123** [comment]
> > 你失败了是因为创建了数据库tothefor后，并没有使用，在创建语句后添加一句 use tothefor;
> 
> > 你失败了是因为创建了数据库tothefor后，并没有使用，在创建语句后添加一句 use tothefor; 就行了
> 
> 还是报错

一样的错误

**Comment by HEEKDragonOne** [comment]
问题解决了

**Comment by xiela123** [comment]
> 问题解决了

怎么解决的

**Comment by HEEKDragonOne** [comment]
数据库的问题

**Comment by HEEKDragonOne** [comment]
不知道为什么id字段从10开始创建的，所以需要改数据库的数据。

**Comment by 1pjllllove** [comment]
解决办法写在了sql语句底部和readme文件中。

**Comment by xiela123** [comment]
> 不知道为什么id字段从10开始创建的，所以需要改数据库的数据。

感谢dalao，菜鸟在此由衷感谢

**Comment by HEEKDragonOne** [comment]
没事，解决了就行。也当是给我找bug了 。哈哈哈

**Comment by HEEKDragonOne** [comment]
项目的sql文件，进行了更新。之前的报错问题不会再出现了。
