### ISSUE TITLE
源码缺少一写文件

### ISSUE THREAD

**Issue by yinlien** [HEEKDragonOne/FirstBlood#3]
![image](https://user-images.githubusercontent.com/102533596/164691397-3fff9d9b-9d27-41a7-89e4-55047d972698.png)
你好，打扰一下。请问是缺少一些包吗？

**Comment by HEEKDragonOne** [comment]
没有缺少

**Comment by HEEKDragonOne** [comment]
你可能需要刷新一下maven

**Comment by HEEKDragonOne** [comment]
你可能需要刷新一下依赖

**Comment by yinlien** [comment]
> 你可能需要刷新一下依赖

是的，我却少了一个依赖。

**Comment by yinlien** [comment]
> 没有缺少



> > 你可能需要刷新一下依赖

请问在测试请求登录时报错出现没有生成token的情况。
![image](https://user-images.githubusercontent.com/102533596/165492487-aed59f27-56cb-46fc-80c9-9e52a77729f0.png)

这大概是什么原因？

**Comment by HEEKDragonOne** [comment]
这应该和token没有关系，应该是建表的问题。你最好删除数据库，使用现在仓库中的sql进行创建。因为这个sql文件是更新后的，之前那个有点问题。

**Comment by yinlien** [comment]
> 

应该是的，我去看看。
